/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/images/3d/scene.glb -K -k 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" position={[3.553, 0.32, -1.263]} rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="1COMPUTER-0_4" position={[-24.287, 5.799, 15.387]} scale={[2.327, 5.804, 5.98]}>
                <mesh name="Object_13001" geometry={nodes.Object_13001.geometry} material={materials['1COMPUTER-0.001']} />
              </group>
              <group name="1PIC-0_9" position={[-16.887, 21.761, -0.693]} rotation={[Math.PI / 2, 0, -0.57]} scale={[8.964, 4.204, 4.87]}>
                <mesh name="Object_23001" geometry={nodes.Object_23001.geometry} material={materials['1PIC-0.001']} />
              </group>
              <group name="2KB-0_14" position={[-2.333, 15.958, 2.159]} rotation={[0, 0.005, 0]} scale={[5.607, 0.175, 1.728]}>
                <mesh name="Object_38001" geometry={nodes.Object_38001.geometry} material={materials['2KB-0.001']} />
                <mesh name="Object_39001" geometry={nodes.Object_39001.geometry} material={materials['1KB-BASE-0.003']} />
                <mesh name="Object_40001" geometry={nodes.Object_40001.geometry} material={materials['1KEYS-0.003']} />
              </group>
              <group name="2PIC-0_8" position={[0, 21.761, -5.754]} rotation={[Math.PI / 2, 0, 0]} scale={[8.964, 4.204, 4.87]}>
                <mesh name="Object_21001" geometry={nodes.Object_21001.geometry} material={materials['2PIC-0.001']} />
              </group>
              <group name="3PIC-0_10" position={[16.987, 21.761, -0.811]} rotation={[Math.PI / 2, 0, 0.552]} scale={[8.964, 4.204, 4.87]}>
                <mesh name="Object_25001" geometry={nodes.Object_25001.geometry} material={materials['3PIC-0.001']} />
              </group>
              <group name="BASS-0_11" position={[0, 4.992, 0.553]} scale={[5.47, 5, 3.905]}>
                <mesh name="Object_27001" geometry={nodes.Object_27001.geometry} material={materials['BASS-0.001']} position={[3.974, 0, 3.265]} rotation={[0, -1.406, 0]} />
              </group>
              <group name="CHAIR-0_2" position={[16.678, 8.418, 24.507]} rotation={[Math.PI, -0.592, Math.PI]} scale={[2.549, 0.243, 2.549]}>
                <mesh name="Object_4001" geometry={nodes.Object_4001.geometry} material={materials['CHAIR-0.001']} position={[3.472, 0, 7.519]} rotation={[0, -0.559, 0]} />
                <mesh name="Object_5001" geometry={nodes.Object_5001.geometry} material={materials['WHEEL-0.001']} position={[3.472, 0, 7.519]} rotation={[0, -0.559, 0]} />
                <mesh name="Object_6001" geometry={nodes.Object_6001.geometry} material={materials['WHEEL-CAP-0.001']} position={[3.472, 0, 7.519]} rotation={[0, -0.559, 0]} />
                <mesh name="Object_7001" geometry={nodes.Object_7001.geometry} material={materials['WHEEL-NUT-0.001']} position={[3.472, 0, 7.519]} rotation={[0, -0.559, 0]} />
                <mesh name="Object_8001" geometry={nodes.Object_8001.geometry} material={materials['CHAIR-LEGS-0.001']} position={[3.472, 0, 7.519]} rotation={[0, -0.559, 0]} />
                <mesh name="Object_9001" geometry={nodes.Object_9001.geometry} material={materials['CHAIR-COVER-0.001']} position={[3.472, 0, 7.519]} rotation={[0, -0.559, 0]} />
              </group>
              <group name="COMPUTER-0_3" position={[-18.152, 5.799, 9.513]} scale={[2.327, 5.804, 5.98]}>
                <mesh name="Object_11001" geometry={nodes.Object_11001.geometry} material={materials['COMPUTER-0.001']} />
              </group>
              <group name="DESK-0_5" position={[0, 15.452, 0]} scale={[29.541, 0.336, 8.492]}>
                <mesh name="Object_15001" geometry={nodes.Object_15001.geometry} material={materials['DESK-0.001']} />
              </group>
              <group name="LAPTOP-0_13" position={[-18.454, 15.918, 9.192]} rotation={[Math.PI, -0.926, Math.PI]} scale={[-5.14, -0.147, -3.341]}>
                <mesh name="Object_31001" geometry={nodes.Object_31001.geometry} material={materials['LAPTOP-0.001']} />
                <mesh name="Object_32001" geometry={nodes.Object_32001.geometry} material={materials['1KB-BASE-0.002']} />
                <mesh name="Object_33001" geometry={nodes.Object_33001.geometry} material={materials['1KEYS-0.002']} />
                <mesh name="Object_34001" geometry={nodes.Object_34001.geometry} material={materials['SCREEN-0.003']} />
                <mesh name="Object_35001" geometry={nodes.Object_35001.geometry} material={materials['SIGN-0.001']} />
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['TAG-0.001']} />
              </group>
              <group name="MAT-0_6" position={[0, 0, 14.147]} scale={[46.718, 46.718, 26.649]}>
                <mesh name="Object_17001" geometry={nodes.Object_17001.geometry} material={materials['MAT-0.001']} />
              </group>
              <group name="MOUSE-0001_15" position={[7.641, 16.001, 4.809]} rotation={[0, 0.415, 0]} scale={[0.751, 0.486, 1.161]}>
                <mesh name="Object_42001" geometry={nodes.Object_42001.geometry} material={materials['MOUSE-0.001']} />
              </group>
              <group name="MOUSEPAD-0_16" position={[7.625, 14.269, 3.664]} scale={3.11}>
                <mesh name="Object_44001" geometry={nodes.Object_44001.geometry} material={materials['MOUSEPAD-0.001']} />
              </group>
              <group name="SCREEN-0_7" position={[0, 21.761, -6.007]} rotation={[Math.PI / 2, 0, 0]} scale={[9.123, 4.323, 5.089]}>
                <mesh name="Object_19001" geometry={nodes.Object_19001.geometry} material={materials['SCREEN-0.002']} />
              </group>
              <group name="SPEAKER-0_12" position={[-27.707, 18.537, 8.063]} rotation={[0, 0.588, 0]} scale={[1.076, 1.75, 0.848]}>
                <mesh name="Object_29001" geometry={nodes.Object_29001.geometry} material={materials['SPEAKER-0.001']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Empty" />
        <mesh name="Cube006" geometry={nodes.Cube006.geometry} material={materials.Bookie} position={[-1.079, 1.647, -1.708]} rotation={[0, -0.084, 0]} />
        <mesh name="Cube007" geometry={nodes.Cube007.geometry} material={materials.Yellow} position={[-0.685, 1.791, -1.643]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.197, 1.102, 1]} />
        <mesh name="Cube008" geometry={nodes.Cube008.geometry} material={materials['Book Variant']} position={[-0.618, 1.773, -1.645]} rotation={[Math.PI / 2, 0.093, -Math.PI / 2]} scale={[1.197, 0.882, 0.879]} />
        <mesh name="Cube009" geometry={nodes.Cube009.geometry} material={materials.Bookie} position={[-1.76, 2.208, 1.249]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1.8, 1.102, 1]} />
        <mesh name="Cube010" geometry={nodes.Cube010.geometry} material={materials['Book Variant']} position={[-1.779, 2.21, 1.189]} rotation={[-Math.PI / 2, -1.57, 0]} scale={[1.8, 0.882, 0.879]} />
        <mesh name="Cube011" geometry={nodes.Cube011.geometry} material={materials['Book Variant']} position={[-1.78, 2.203, 1.32]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1.8, 1.102, 1]} />
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.Yellow} position={[-1.815, 2.918, 1.243]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1.8, 1.102, 1]} />
        <mesh name="Cube013" geometry={nodes.Cube013.geometry} material={materials.Yellow} position={[-1.834, 2.921, 1.183]} rotation={[-Math.PI / 2, -1.57, 0]} scale={[1.8, 0.882, 0.879]} />
        <mesh name="Cube014" geometry={nodes.Cube014.geometry} material={materials.Bookie} position={[-1.834, 2.913, 1.315]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={[1.8, 1.102, 1]} />
        <mesh name="Cube015" geometry={nodes.Cube015.geometry} material={materials.Bookie} position={[-1.834, 2.868, 1.403]} rotation={[-1.673, -1.571, 0]} scale={[1.416, 1.102, 1]} />
        <mesh name="Cube016" geometry={nodes.Cube016.geometry} material={materials.Yellow} position={[-1.682, 1.975, 0.957]} scale={[1.8, 1.102, 0.85]} />
        <mesh name="Circle005" geometry={nodes.Circle005.geometry} material={materials['Material.005']} position={[-1.656, 1.949, 0.698]} rotation={[0, 1.036, 0]} scale={[0.056, 0.07, 0.056]}>
          <mesh name="Sphere006" geometry={nodes.Sphere006.geometry} material={materials.Cacti} position={[0, 1.784, 0]} scale={[0.926, 1.647, 0.926]} />
          <mesh name="Sphere007" geometry={nodes.Sphere007.geometry} material={materials.Cacti} position={[0.736, 2.387, -0.294]} rotation={[0, 0, -0.617]} scale={[0.473, 0.841, 0.473]} />
          <mesh name="Sphere008" geometry={nodes.Sphere008.geometry} material={materials.Cacti} position={[-0.136, 2.159, 0.762]} rotation={[1.046, 0.814, -0.314]} scale={[0.372, 0.661, 0.372]} />
        </mesh>
        <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={materials['Material.005']} position={[-1.594, 0.28, 1.563]} rotation={[0, 1.036, 0]} scale={[0.134, 0.229, 0.134]}>
          <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.004']} position={[-1.078, 1.534, 0.429]} rotation={[0.447, -0.998, 0.446]} scale={[7.49, 5.458, 7.382]} />
          <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={materials['Material.004']} position={[-1.223, 1.856, -0.463]} rotation={[Math.PI, -1.402, Math.PI]} scale={[6.46, 4.279, 6.46]} />
          <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.004']} position={[0.732, 2.042, -0.234]} rotation={[-Math.PI, 0.578, -Math.PI]} scale={[5.889, 4.47, 5.889]} />
          <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.004']} position={[0.601, 1.856, 0.847]} rotation={[0.051, 0.973, -0.195]} scale={[5.458, 4.232, 5.478]} />
          <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials['Material.004']} position={[-1.038, 2.218, 0.416]} rotation={[0, -0.792, 0]} scale={[6.239, 5.679, 6.239]} />
          <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.004']} position={[-1.176, 2.617, -0.433]} rotation={[2.481, -1.37, 2.263]} scale={[6.182, 8.153, 6.194]} />
          <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['Material.004']} position={[0.685, 2.847, -0.216]} rotation={[-Math.PI, 0.3, -Math.PI]} scale={[5.606, 5.534, 5.606]} />
          <mesh name="Plane007" geometry={nodes.Plane007.geometry} material={materials['Material.004']} position={[0.561, 2.617, 0.813]} rotation={[0, 0.757, 0]} scale={[5.22, 5.153, 5.22]} />
          <mesh name="Plane008" geometry={nodes.Plane008.geometry} material={materials['Material.004']} position={[-0.64, 3.19, 0.733]} rotation={[0, -0.557, 0]} scale={[4.504, 3.88, 4.504]} />
          <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['Material.004']} position={[0.023, 3.359, -0.469]} rotation={[Math.PI, -0.884, Math.PI]} scale={[4.106, 4.053, 4.106]} />
          <mesh name="Plane010" geometry={nodes.Plane010.geometry} material={materials['Material.004']} position={[0.686, 3.19, -0.1]} rotation={[-Math.PI, 1.201, -Math.PI]} scale={[3.823, 3.774, 3.823]} />
        </mesh>
        <group name="Circle007" position={[-1.793, 2.617, 0.682]} scale={-0.071}>
          <mesh name="Circle007_1" geometry={nodes.Circle007_1.geometry} material={materials.Candle} />
          <mesh name="Circle007_2" geometry={nodes.Circle007_2.geometry} material={materials['Candle light']} />
        </group>
        <mesh name="CharacterSpot" geometry={nodes.CharacterSpot.geometry} material={nodes.CharacterSpot.material} position={[3.393, 0.374, -0.761]} rotation={[-Math.PI, 0.146, -Math.PI]} scale={[0.452, 1, 0.452]}>
          <group name="Armature" position={[-3.477, -0.315, 0.493]} rotation={[Math.PI / 2, 0, 0]} scale={[2.212, 2.212, 1]}>
            <primitive object={nodes.Hips} />
          </group>
          <skinnedMesh name="Wolf3D_Glasses" geometry={nodes.Wolf3D_Glasses.geometry} material={materials['Wolf3D_Glasses.003']} skeleton={nodes.Wolf3D_Glasses.skeleton} />
          <skinnedMesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={materials['Wolf3D_Hair.003']} skeleton={nodes.Wolf3D_Hair.skeleton} />
          <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials['Wolf3D_Eye.003']} skeleton={nodes.EyeLeft.skeleton} />
          <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials['Wolf3D_Eye.003']} skeleton={nodes.EyeRight.skeleton} />
          <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials['Wolf3D_Body.003']} skeleton={nodes.Wolf3D_Body.skeleton} />
          <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials['Wolf3D_Skin.003']} skeleton={nodes.Wolf3D_Head.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials['Wolf3D_Outfit_Bottom.003']} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials['Wolf3D_Outfit_Footwear.003']} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials['Wolf3D_Outfit_Top.003']} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
          <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials['Wolf3D_Teeth.003']} skeleton={nodes.Wolf3D_Teeth.skeleton} />
        </mesh>
        <mesh name="Walls" geometry={nodes.Walls.geometry} material={materials.Walls} position={[0, 2.244, 0]} />
        <mesh name="Tiles" geometry={nodes.Tiles.geometry} material={materials.Floor} position={[0, 2.244, 0]} />
        <mesh name="Tiles001" geometry={nodes.Tiles001.geometry} material={materials.Floor} position={[4.004, 2.246, -0.006]} />
        <mesh name="Wall_Floor_Part" geometry={nodes.Wall_Floor_Part.geometry} material={materials['Lower floor']} position={[0, 2.244, 0]} />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.White} position={[0.945, 2.689, -2.107]} scale={[0.786, 1.258, 0.205]} />
        <mesh name="Cylinder005" geometry={nodes.Cylinder005.geometry} material={materials['shelf handles']} position={[1.503, 0.135, -0.878]} rotation={[Math.PI / 2, 0, 0]} scale={[0.021, 0.007, 0.021]} />
        <mesh name="Table_Top001" geometry={nodes.Table_Top001.geometry} material={materials['Brown table top']} position={[-1.011, 1.554, -1.725]} scale={[0.676, 0.879, 0.675]} />
        <mesh name="Table_Top002" geometry={nodes.Table_Top002.geometry} material={materials['Brown table top']} position={[-1.658, 1.887, 1.025]} rotation={[0, Math.PI / 2, 0]} scale={[0.676, 0.879, 0.675]} />
        <mesh name="Table_Top003" geometry={nodes.Table_Top003.geometry} material={materials['Brown table top']} position={[-1.658, 2.595, 1.025]} rotation={[0, Math.PI / 2, 0]} scale={[0.676, 0.879, 0.675]} />
        <mesh name="Sheets" geometry={nodes.Sheets.geometry} material={materials.Sheets} position={[-0.961, 0.87, -0.456]} scale={[1.108, 1, 1.138]}>
          <mesh name="Bedframe" geometry={nodes.Bedframe.geometry} material={materials['Brown table top']} position={[0.786, -0.158, 1.218]} />
          <mesh name="Matras" geometry={nodes.Matras.geometry} material={materials.Walls} />
          <mesh name="Pillow" geometry={nodes.Pillow.geometry} material={materials.Sheets} position={[-0.274, 0.116, -1.021]} rotation={[0.356, 0, 0]} scale={[0.303, 0.119, 0.294]} />
          <mesh name="Pillow_small" geometry={nodes.Pillow_small.geometry} material={materials.Yellow} position={[-0.352, 0.116, -0.736]} rotation={[0.553, 0.178, -0.023]} scale={[0.236, 0.093, 0.23]} />
        </mesh>
        <mesh name="Window_Frame" geometry={nodes.Window_Frame.geometry} material={nodes.Window_Frame.material} position={[0.945, 2.689, -2.107]} />
        <group name="Upper_Window" position={[0.945, 2.689, -2.249]}>
          <mesh name="Cube009_1" geometry={nodes.Cube009_1.geometry} material={materials.White} />
          <mesh name="Cube009_2" geometry={nodes.Cube009_2.geometry} material={materials['Window light']} />
        </group>
        <group name="Lower_Window" position={[0.945, 1.431, -2.32]}>
          <mesh name="Cube010_1" geometry={nodes.Cube010_1.geometry} material={materials.White} />
          <mesh name="Cube010_2" geometry={nodes.Cube010_2.geometry} material={materials['Window light']} />
        </group>
        <mesh name="Shade" geometry={nodes.Shade.geometry} material={materials['Material.006']} position={[0.945, 2.689, -2.007]} scale={[1, 1, 0.147]} />
        <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0.945, 2.459, -2.007]} rotation={[0, 0, -Math.PI / 2]} scale={[0.012, 0.79, 0.012]} />
        <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[0.945, 3.929, -2.007]} rotation={[0, 0, -Math.PI / 2]} scale={[0.034, 0.79, 0.034]} />
        <mesh name="Cylinder009" geometry={nodes.Cylinder009.geometry} material={materials['chair balls']} position={[0.739, 0.086, -0.613]} rotation={[Math.PI / 2, 0, 0.53]} scale={[0.039, 0.033, 0.039]} />
        <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials['Poster.001']} position={[-0.965, 3.107, -1.982]} rotation={[Math.PI / 2, 0, 0]} scale={[0.518, 1, 0.784]} />
        <group name="Table_Top004" position={[4.777, 2.955, -2.025]} rotation={[Math.PI / 2, 0, 0]} scale={1.587}>
          <mesh name="Cube020" geometry={nodes.Cube020.geometry} material={materials.White} />
          <mesh name="Cube020_1" geometry={nodes.Cube020_1.geometry} material={materials.PicBg} />
        </group>
        <group name="Table_Top005" position={[3.359, 3.166, -2.025]} rotation={[Math.PI / 2, 0, 0]} scale={[1.347, 1.587, 1.252]}>
          <mesh name="Cube021" geometry={nodes.Cube021.geometry} material={materials.White} />
          <mesh name="Cube021_1" geometry={nodes.Cube021_1.geometry} material={materials['pic Bg 1']} />
        </group>
        <group name="Table_Top006" position={[3.359, 3.052, -2.025]} rotation={[-Math.PI / 2, -0.013, -Math.PI]} scale={[1.347, 1.587, 1.252]}>
          <mesh name="Cube022" geometry={nodes.Cube022.geometry} material={materials.White} />
          <mesh name="Cube022_1" geometry={nodes.Cube022_1.geometry} material={materials['pic bg 2']} />
        </group>
        <mesh name="Plane012" geometry={nodes.Plane012.geometry} material={materials.Walls} position={[2.986, 0.246, 0.046]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
